version: '3.8'

services:
  air-detr-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: air_detr_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
